server:
  port: 8082

spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  liquibase:
    change-log: classpath:dbchangelog/db.changelog-master.xml

  jpa:
    hibernate:
      ddl-auto: validate

logging:
  level:
    root: WARN