name: CI Package External Config

on:
  push:
    branches: [main]

jobs:
  build-external:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build without internal YAML
        run: mvn clean package -Pno-embedded-config

      - name: Check target folder
        run: ls -l target

      - name: Smoke test with CI config
        run: |
          echo "Starting app..."
          java -jar target/*.jar --spring.config.location=file:./config/application-ci.yaml > app.log 2>&1 &
          sleep 30
          echo "App logs:"
          cat app.log
          curl -f http://localhost:8080/actuator/health

      - name: Upload JAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: user4-external-artifact
          path: target/*.jar